Fire_Route/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_trans.urls')),
    path('data_trans/', include('data_trans.urls')),
    path('users/', include('users.urls'))
]

data_trans/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_data_from_web),
    path('data/', views.update_data),
]

users/urls.py
from django.urls import path
from users import views
app_name = 'users'

urlpatterns = [
    path('login_check', views.login_check),
    path('life', views.escape_route, name='escape_route'),
    path('save', views.rescue_route),
    path('line', views.make_line),
    path('loginout', views.login_out_view, name='login_out')
]

data_trans/models.py
from django.db import models


# Create your models here.
class data_trans_Profile(models.Model):
    id = models.AutoField(verbose_name="编号", primary_key=True)
    data_in_01 = models.CharField(verbose_name="执行码", max_length=10, default=None, null=True)

    class Meta:
        db_table = "data_trans_info"

users/models.py
from django.db import models


# Create your models here.

class usersProfile(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=30, primary_key=True)
    password = models.CharField(verbose_name='密码', max_length=30)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'users_info'

data_trans/views.py
from django.shortcuts import render
from data_trans.models import data_trans_Profile
from django.http import JsonResponse


# Create your views here.
def get_data_from_web(request):
    # ""填硬件方的名字
    data_trans_01 = request.GET.get("p")
    data_trans_Profile.objects.create(data_in_01=data_trans_01)
    return render(request, "homepage.html")


def update_data(request):
    mysql_data = data_trans_Profile.objects.order_by("-id").first()
    data_trans_01 = mysql_data.data_in_01
    result = {"code": 200, "data": {"data_train_01": data_trans_01}}
    return JsonResponse(result)

users/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from users.models import usersProfile
import jwt
from django.conf import settings
import time


# Create your views here.
def escape_route(request):
    return render(request, "escape_route.html")


def rescue_route(request):
    return render(request, "rescue_route.html")


def make_line(request):
    return render(request, "make_line.html")


def login_check(request):
    if request.method != 'POST':
        result = {'code': 10200, 'error': 'Please use POST'}
        return JsonResponse(result)
    json_str = request.body
    json_obj = json.loads(json_str)
    username = json_obj['username']
    password = json_obj['password']
    # 校验用户名和密码
    try:
        user = usersProfile.objects.get(username=username)
    except Exception as e:
        result = {'code': 10201, 'error': 'The username or password is wrong'}
        return JsonResponse(result)
    if password != user.password:
        result = {'code': 10202, 'error': 'The username or password is wrong'}
        return JsonResponse(result)
    # 记录会话状态
    token = make_token(username)
    result = {'code': 200, 'username': username, 'data': {'token': token}}
    return JsonResponse(result)


# 生成token
def make_token(username, expire=3600 * 24):
    # 在settings中去配置key
    key = settings.JWT_TOKEN_KEY
    new_t = time.time()
    payload_data = {'username': username, 'exp': new_t + expire}
    # 生成的jwt是字节串
    return jwt.encode(payload_data, key, algorithm='HS256')


def login_out_view(request):
    # 删除session值：
    # if 'username' in request.session:
    #     del request.session['username']
    # if 'uid' in request.session:
    #     del  request.session['uid']
    # 删除Cookie：
    # resp=HttpResponseRedirect('/index')
    # if 'username' in request.COOKIES:
    #     resp.delete_cookie('username')
    # if 'uid' in request.COOKIES:
    #     resp.delete_cookie('uid')
    return render(request, 'homepage.html')

templates/escape_route.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <title>火灾逃生路线</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- Plugins css -->
    <link href="{% static 'libs/flatpickr/flatpickr.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/selectize/css/selectize.bootstrap3.css' %}" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="{% static 'css/config/modern/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
          id="bs-default-stylesheet" />
    <link href="{% static 'css/config/modern/app.min.css' %}" rel="stylesheet" type="text/css" id="app-default-stylesheet" />

    <link href="{% static 'css/config/modern/bootstrap-dark.min.css' %}" rel="stylesheet" type="text/css"
          id="bs-dark-stylesheet" />
    <link href="{% static 'css/config/modern/app-dark.min.css' %}" rel="stylesheet" type="text/css"
          id="app-dark-stylesheet" />

    <!-- icons -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
</head>

<!-- body start -->

<body class="loading" data-layout-mode="detached"
    data-layout='{"mode": "light", "width": "fluid", "menuPosition": "fixed", "sidebar": { "color": "light", "size": "default", "showuser": true}, "topbar": {"color": "dark"}, "showRightSidebarOnPageLoad": true}'>
    <div id="wrapper">

        <!-- Topbar Start -->
        <div class="navbar-custom">
            <div class="container-fluid">
                <ul class="list-unstyled topnav-menu float-end mb-0">
                    <!-- 用户登录界面 -->
                    <li class="dropdown notification-list topbar-dropdown">
                        <a class="nav-link dropdown-toggle nav-user me-0 waves-effect waves-light"
                            data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                            aria-expanded="false">
                            <img src="{% static 'images/users/user-6.jpg' %}" alt="user-image" class="rounded-circle">
                            <span class="pro-user-name ms-1">
                                Stanley <i class="mdi mdi-chevron-down"></i>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end profile-dropdown ">
                            <a href="{% url 'users:login_out' %}" class="dropdown-item notify-item">
                                <i class="fe-log-out"></i>
                                <span>退出账号</span>
                            </a>

                        </div>
                    </li>
                </ul>

                <!-- LOGO -->
                <div class="logo-box">
                    <a href="/" class="logo logo-dark text-center">
                        <span class="logo-sm">
                            <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                            <!-- <span class="logo-lg-text-light">UBold</span> -->
                        </span>
                        <span class="logo-lg">
                            <img src="{% static 'images/logo-dark.png' %}" alt="" height="20">
                            <!-- <span class="logo-lg-text-light">U</span> -->
                        </span>
                    </a>

                    <a href="/" class="logo logo-light text-center">
                        <span class="logo-sm">
                            <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="{% static 'images/logo-light.png' %}" alt="" height="20">
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="left-side-menu">

            <div class="h-100" data-simplebar>
                <div id="sidebar-menu">

                    <ul id="side-menu">

                        <li>
                            <a href="#sidebarDashboards" data-bs-toggle="collapse">
                                <i data-feather="airplay"></i>
                                <span> 路线规划 </span>
                            </a>
                            <div class="collapse" id="sidebarDashboards">
                                <ul class="nav-second-level">
                                    <li>
                                        <a href="http://127.0.0.1:8000/users/life">火灾逃生路线</a>
                                    </li>
                                    <li>
                                        <a href="http://127.0.0.1:8000/users/save">火灾救援路线</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="content-page">
            <div class="content">

                <!-- Start Content-->
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <h4 class="page-title">火灾逃生路线</h4>
                            </div>
                        </div>
                    </div>
                    <!--  title -->

                    <div class="row" id="1">
                        <iframe src="http://127.0.0.1:8000/users/line" frameborder="0" align="center" width="800" height="550"></iframe>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- Vendor js -->
    <script src="{% static 'js/vendor.min.js' %}"></script>

    <!-- Plugins js-->
    <script src="{% static 'libs/flatpickr/flatpickr.min.js' %}"></script>
    <script src="{% static 'libs/apexcharts/apexcharts.min.js' %}"></script>

    <script src="{% static 'libs/selectize/js/standalone/selectize.min.js' %}"></script>

    <!-- Dashboar 1 init js-->
    <script src="{% static 'js/pages/dashboard-1.init.js' %}"></script>

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
    <div style="display:none"><a href="http://www.bootstrapmb.com">bootstrapmb</a></div>
</body>

</html>

templates/make_line.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        #tutorial {
            border: 1px solid black;
            height: 480px;
            width: 720px;
        }
    </style>
        <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
    <canvas id="tutorial" width="500" height="300">
        你的浏览器不支持 canvas，请升级你的浏览器。
    </canvas>

</body>

<script type="text/javascript">
    function f() {
        var a;
    $.ajax({
        type: "get",
        url: "http://127.0.0.1:8000/ins/data",
        async: false,
        success: function (result) {
            if (result['code'] == 200) {
                a =result['data']['zero_or_one'];
                console.log(a);
            }
        }
    });
    return a;
    }
    </script>
    <script>
    {#console.log(a);#}
    function draw(a) {
        var canvas = document.getElementById('tutorial');
        if (!canvas.getContext) return;
        var ctx = canvas.getContext("2d");
        if (a == 0) {

            ctx.fillRect(100, 0, 100, 50);
            ctx.fillRect(280, 0, 100, 50);
            ctx.fillRect(0, 30, 50, 100);
            ctx.fillRect(0, 150, 50, 100);
            ctx.fillRect(280, 250, 100, 50);
            ctx.fillRect(100, 250, 100, 50);
            ctx.fillRect(450, 30, 50, 100);
            ctx.fillRect(450, 150, 50, 100);
            ctx.fillRect(100, 80, 50, 140);

            ctx.fillRect(330, 80, 50, 140);
        }
        else {
            ctx.fillRect(100, 0, 100, 50);
            ctx.fillRect(280, 0, 100, 50);
            ctx.fillRect(0, 30, 50, 100);
            ctx.fillRect(0, 150, 50, 100);
            ctx.fillRect(280, 250, 100, 50);
            ctx.fillRect(100, 250, 100, 50);
            ctx.fillRect(450, 30, 50, 100);
            ctx.fillRect(450, 150, 50, 100);
            ctx.fillRect(100, 80, 50, 140);
            ctx.fillRect(330, 80, 50, 140);
            ctx.fillStyle = "rgb(225,0,0)";
            ctx.fillRect(400, 250, 30, 30);
            function drawup(x, y, length) {
                var len = 0;
                function upline() {
                    var canvas = document.getElementById('tutorial');
                    if (!canvas.getContext) return;
                    var ctx = canvas.getContext("2d");
                    if (len <= length) {
                        ctx.moveTo(x, y);
                        ctx.lineTo(x, --y);
                        len++;
                        ctx.strokeStyle = "rgba(0,255,0,1)";
                        ctx.stroke();
                    }
                }
                setInterval(upline, 3)
            }

            function drawright(x, y, length) {
                var len = 0;
                function rightline() {
                    var canvas = document.getElementById('tutorial');
                    if (!canvas.getContext) return;
                    var ctx = canvas.getContext("2d");
                    if (len <= length) {
                        ctx.moveTo(x, y);
                        ctx.lineTo(++x, y);
                        len++;
                        ctx.strokeStyle = "rgba(0,255,0,1)";
                        ctx.stroke();
                    }
                }
                setInterval(rightline, 3)
            }

            function drawdown(x, y, length) {
                var len = 0;
                function rightline() {
                    var canvas = document.getElementById('tutorial');
                    if (!canvas.getContext) return;
                    var ctx = canvas.getContext("2d");
                    if (len <= length) {
                        ctx.moveTo(x, y);
                        ctx.lineTo(x, ++y);
                        len++;
                        ctx.strokeStyle = "rgba(0,255,0,1)";
                        ctx.stroke();
                    }
                }
                setInterval(rightline, 3)
            }

            function drawlift(x, y, length) {
                var len = 0;
                function rightline() {
                    var canvas = document.getElementById('tutorial');
                    if (!canvas.getContext) return;
                    var ctx = canvas.getContext("2d");
                    if (len <= length) {
                        ctx.moveTo(x, y);
                        ctx.lineTo(--x, y);
                        len++;
                        ctx.strokeStyle = "rgba(0,255,0,1)";
                        ctx.stroke();
                    }
                }
                setInterval(rightline, 3)
            }
            // 左下
            drawright(50, 200, 25);
            drawdown(75, 200, 200);
            drawup(125, 250, 10);
            drawlift(125, 240, 50);

            //左上
            drawright(50, 85, 25);
            drawup(75, 85, 90);
            drawdown(150, 50, 15);
            drawlift(150, 65, 75);
            drawlift(100, 150, 25);
            drawup(75, 150, 75);

            //右上
            drawdown(330, 50, 15);
            drawright(330, 65, 90);
            drawlift(450, 85, 30);
            drawup(420, 85, 85);
            drawright(380, 150, 40);
            drawup(420, 150, 70);

            //右下
            drawlift(450, 200, 30);
            drawup(420, 200, 60);

            drawup(330, 250, 10);
            drawlift(330, 240, 210);
        }
    }
    var a=f();
    console.log(a);
    draw(a);

</script>

<script>
    setTimeout(function () { location.reload() }, 7000)
</script>

</html>

templates/rescue_route.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <title>火灾救援路线</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- Plugins css -->
    <link href="{% static 'libs/flatpickr/flatpickr.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/selectize/css/selectize.bootstrap3.css' %}" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="{% static 'css/config/modern/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
          id="bs-default-stylesheet" />
    <link href="{% static 'css/config/modern/app.min.css' %} " rel="stylesheet" type="text/css" id="app-default-stylesheet" />

    <link href="{% static 'css/config/modern/bootstrap-dark.min.css' %} " rel="stylesheet" type="text/css"
          id="bs-dark-stylesheet" />
    <link href="{% static 'css/config/modern/app-dark.min.css' %} " rel="stylesheet" type="text/css"
          id="app-dark-stylesheet" />

    <!-- icons -->
    <link href="{% static 'css/icons.min.css' %} " rel="stylesheet" type="text/css" />
    <style>
        .row1 {}
    </style>
</head>

<!-- body start -->

<body class="loading" data-layout-mode="detached"
    data-layout='{"mode": "light", "width": "fluid", "menuPosition": "fixed", "sidebar": { "color": "light", "size": "default", "showuser": true}, "topbar": {"color": "dark"}, "showRightSidebarOnPageLoad": true}'>
    <div id="wrapper">

        <!-- Topbar Start -->
        <div class="navbar-custom">
            <div class="container-fluid">
                <ul class="list-unstyled topnav-menu float-end mb-0">
                    <!-- 用户登录界面 -->
                    <li class="dropdown notification-list topbar-dropdown">
                        <a class="nav-link dropdown-toggle nav-user me-0 waves-effect waves-light"
                            data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                            aria-expanded="false">
                            <img src="{% static 'images/users/user-6.jpg' %} " alt="user-image" class="rounded-circle">
                            <span class="pro-user-name ms-1">
                                Stanley <i class="mdi mdi-chevron-down"></i>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end profile-dropdown ">
                            <a href="{% url 'users:login_out' %}" class="dropdown-item notify-item">
                                <i class="fe-log-out"></i>
                                <span>退出账号</span>
                            </a>

                        </div>
                    </li>
                </ul>

                <!-- LOGO -->
                <div class="logo-box">
                    <a href="/" class="logo logo-dark text-center">
                        <span class="logo-sm">
                            <img src="{% static 'images/logo-sm.png' %} " alt="" height="22">
                            <!-- <span class="logo-lg-text-light">UBold</span> -->
                        </span>
                        <span class="logo-lg">
                            <img src="{% static 'images/logo-dark.png' %} " alt="" height="20">
                            <!-- <span class="logo-lg-text-light">U</span> -->
                        </span>
                    </a>

                    <a href="/" class="logo logo-light text-center">
                        <span class="logo-sm">
                            <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="{% static 'images/logo-light.png' %}" alt="" height="20">
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="left-side-menu">

            <div class="h-100" data-simplebar>
                <div id="sidebar-menu">

                    <ul id="side-menu">

                        <li>
                            <a href="#sidebarDashboards" data-bs-toggle="collapse">
                                <i data-feather="airplay"></i>
                                <span> 路线规划 </span>
                            </a>
                            <div class="collapse" id="sidebarDashboards">
                                <ul class="nav-second-level">
                                    <li>
                                        <a href="http://127.0.0.1:8000/users/life">火灾逃生路线</a>
                                    </li>
                                    <li>
                                        <a href="http://127.0.0.1:8000/users/save">火灾救援路线</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="content-page">
            <div class="content">

                <!-- Start Content-->
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <h4 class="page-title">火灾救援路线</h4>
                            </div>
                        </div>
                    </div>
                    <!--  title -->

                    <div class="row" id="1">
                        <iframe src="http://127.0.0.1:8000/users/line" frameborder="0" align="center" width="800" height="550"></iframe>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- Vendor js -->
    <script src="{% static 'js/vendor.min.js' %} "></script>

    <!-- Plugins js-->
    <script src="{% static 'libs/flatpickr/flatpickr.min.js' %} "></script>
    <script src="{% static 'libs/apexcharts/apexcharts.min.j' %} "></script>

    <script src="{% static 'libs/selectize/js/standalone/selectize.min.js' %}"></script>

    <!-- Dashboar 1 init js-->
    <script src="{% static 'js/pages/dashboard-1.init.js' %}"></script>

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
    <div style="display:none"><a href="http://www.bootstrapmb.com">bootstrapmb</a></div>
</body>

</html>